import os
import zipfile
from pathlib import Path

OUTPUT_DIR = "generated_projects"

def create_project_structure(api_code: str, project_name: str) -> str:
    project_path = Path(OUTPUT_DIR) / project_name
    project_path.mkdir(parents=True, exist_ok=True)

    main_file = project_path / "main.py"
    main_file.write_text(api_code)

    requirements = project_path / "requirements.txt"
    requirements.write_text(
        "fastapi\nuvicorn\npydantic\nsqlalchemy\n"
    )

    readme = project_path / "README.md"
    readme.write_text(f"""# {project_name}

## Generated by AI API Builder 🤖

## Setup:
```bash
pip install -r requirements.txt
uvicorn main:app --reload
""")
zip_path = Path(OUTPUT_DIR) / f"{project_name}.zip"
with zipfile.ZipFile(zip_path, "w") as zipf:
    for file in project_path.rglob("*"):
        zipf.write(file, file.relative_to(project_path))

return str(zip_path)