import os
import zipfile
from pathlib import Path

OUTPUT_DIR = "generated_projects"

<<<<<<< HEAD
=======
def parse_files(raw_code: str) -> dict:
    files = {}
    current_file = None
    current_lines = []

    for line in raw_code.splitlines():
        if line.strip().startswith("# ===") and line.strip().endswith("==="):
            if current_file:
                files[current_file] = "\n".join(current_lines).strip()
            current_file = line.strip().replace("# ===", "").replace("===", "").strip()
            current_lines = []
        else:
            current_lines.append(line)

    if current_file:
        files[current_file] = "\n".join(current_lines).strip()

    if not files:
        files["main.py"] = raw_code.strip()

    return files

>>>>>>> f62253e (ne)
def create_project_structure(api_code: str, project_name: str) -> str:
    project_path = Path(OUTPUT_DIR) / project_name
    project_path.mkdir(parents=True, exist_ok=True)

<<<<<<< HEAD
    main_file = project_path / "main.py"
    main_file.write_text(api_code)
=======
    files = parse_files(api_code)

    for filename, content in files.items():
        file_path = project_path / filename
        file_path.write_text(content)
>>>>>>> f62253e (ne)

    requirements = project_path / "requirements.txt"
    requirements.write_text("fastapi\nuvicorn\npydantic\nsqlalchemy\n")

<<<<<<< HEAD
=======
    file_list = "\n".join(f"- {f}" for f in files.keys())
>>>>>>> f62253e (ne)
    readme = project_path / "README.md"
    readme.write_text(f"""# {project_name}

## Generated by AI API Builder 🤖

## Files:
{file_list}

## Setup:
```bash
pip install -r requirements.txt
uvicorn main:app --reload
<<<<<<< HEAD
""")
zip_path = Path(OUTPUT_DIR) / f"{project_name}.zip"
with zipfile.ZipFile(zip_path, "w") as zipf:
    for file in project_path.rglob("*"):
        zipf.write(file, file.relative_to(project_path))

return str(zip_path)
=======
```
""")

    zip_path = Path(OUTPUT_DIR) / f"{project_name}.zip"
    with zipfile.ZipFile(zip_path, "w") as zipf:
        for file in project_path.rglob("*"):
            zipf.write(file, file.relative_to(project_path))

    return str(zip_path)
>>>>>>> f62253e (ne)
